#!/bin/python3

import math
import os
import random
import re
import sys


# Complete the hourglassSum function below.
def hourglassSum(arr):
    def get_x_y(x, y):
        """
        Given x, y coordinates, get the value at cooresponding to the given indices
        """

        return arr[y][x]

    def get_adjacent(x, y) -> list:
        """
        Given an x, y coordinate, get the adjacent cells and return them in a list
        """

        return [get_x_y(x, y)] + [get_x_y(i, y - 1) for i in range(x - 1, x + 2)] \
               + [get_x_y(i, y + 1) for i in range(x - 1, x + 2)]

    return max(sum(get_adjacent(i, j)) for i in range(1, 5) for j in range(1, 5))


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
